### ISSUE TITLE
Update button style

### ISSUE THREAD

**Issue by hannavas** [codecooperative/codecooperative.org#33]
- [x] Border should be 1px
- [x] Button height should be 52px
- [x] Left and right padding around text should be 24px
- [x] Top and bottom padding around text should be 14px
- [x] On hover, background (for the text part of the button) should change to F8F8F8
- [x] Arrow should be a custom arrow (I'll send you the SVG) that has 20px left and right padding
- [x] Fix Button transition on hover

**Comment by adekunleoduye** [comment]
Done!
